name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  publish-helm-chart:
    runs-on: self-hosted, Linux, X64
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Setup MinIO Client
        run: |
          curl -sL https://dl.min.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc
          chmod +x /usr/local/bin/mc

      - name: Increment Version and Package
        run: |
          CHART_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          CHART_NAME=$(grep '^name:' Chart.yaml | awk '{print $2}')
          
          # Simple patch version increment
          NEW_VERSION=$(echo $CHART_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          
          # Update Chart.yaml
          sed -i "s/version: ${CHART_VERSION}/version: ${NEW_VERSION}/" Chart.yaml
          
          # Package with new version
          helm package . --version ${NEW_VERSION}
          
          PACKAGE_NAME="${CHART_NAME}-${NEW_VERSION}.tgz"
          echo "PACKAGE_NAME=${PACKAGE_NAME}" >> $GITHUB_ENV
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo $NEW_VERSION

    